"""
Scoped DynamoDB IAM roles for per-request tenant scope enforcement.

This module defines the two least-privilege IAM roles that the tool Lambdas
assume (via ``sts:AssumeRole`` with a per-request ``dynamodb:LeadingKeys``
session policy) to touch ``DocumentsTable`` — never their own broad execution
roles:

- ``DocumentsAccessRole`` (READ): identity policy grants ``dynamodb:GetItem`` +
  ``dynamodb:Query`` on ``DocumentsTable``. Assumed by the read-tool
  (``read_document`` / ``search_documents``) Lambda execution roles. The
  per-request session policy narrows this broad grant to a single served
  partition.
- ``DocumentsWriteRole`` (WRITE): identity policy grants ONLY
  ``dynamodb:UpdateItem`` on ``DocumentsTable`` (no read actions). Assumed by
  the ``reply`` Lambda execution role. The per-request session policy narrows
  it to the served partition.

Read and write capabilities are split across two roles (least-privilege
separation): a read-path tool can never write and the write-path tool can never
read.

TWO GATES, NOT ONE — READ THIS BEFORE WIDENING ANYTHING:
    Originally each identity policy granted its actions on the WHOLE table with
    no partition constraint, and one shared role served every tenant. Tenant
    separation lived ENTIRELY in the per-request inline session policy built by
    ``interceptor/scoped_credentials.py:build_session_policy``. That is
    architecturally valid — a session policy can only intersect (narrow) the
    identity policy — but it made correctness rest on a single enforcement
    point: any ``AssumeRole`` on these roles that omitted the session policy
    yielded full cross-tenant read/write of every partition, including
    ``infra-secrets`` and ``hr-data``. No second gate existed: not in the
    identity policy, not in the trust policy, not in Cedar.

    These roles now carry an ABAC condition of their own (see
    ``_scope_tag_conditions``): the interceptor passes a ``scope`` SESSION TAG on
    ``AssumeRole``, and each identity policy requires the request's
    ``dynamodb:LeadingKeys`` to match ``${aws:PrincipalTag/scope}``. Two
    independent things must now hold for a cross-partition read to succeed —
    the session must be tagged with the foreign scope AND the session policy
    must allow it — and the tag is checked by the role itself, outside the
    caller's code path. ``cdk/lambda_iam.py`` closes the remaining hole by
    requiring the tag in each role's TRUST policy, so an untagged
    ``AssumeRole`` is rejected before any credential is minted.

TRUST-POLICY ORDERING (READ THIS) — the trust principals are wired LATER in
``cdk/lambda_iam.py``, NOT here:
    Each role's TRUST policy must name the specific tool Lambda execution roles
    as principals (e.g. ``arn:...role/<read_document-exec-role>``). But those
    Lambda functions — and their CDK-autogenerated execution roles — are created
    in ``cdk/scoped_credentials_stack.py`` AFTER ``create_data_resources()`` runs, so the
    exec-role principals DO NOT EXIST yet when these roles are constructed. We
    therefore create both roles now with a TEMPORARY, non-forgeable placeholder
    trust (``iam.AccountPrincipal`` of THIS account) and expose the ``iam.Role``
    constructs so the Lambda IAM wiring can attach the exact exec-role
    principals.

    Why ``AccountPrincipal`` is safe as a TEMPORARY placeholder (and not a
    wide-open door): an account-principal trust does NOT itself let anyone
    assume the role — it DELEGATES the assume decision to IAM identity-based
    policies within this account (AWS "delegate authority to the account"
    semantics). No identity in the stack is granted ``sts:AssumeRole`` on these
    roles until the Lambda IAM wiring grants it, and that wiring grants it ONLY
    to the specific tool exec roles. So in the current stack nothing can
    actually assume these roles. It is NOT ``AnyPrincipal``/``*`` and is NOT
    assumable cross-account.

    RESOLVED: the trust is finalized in ``cdk/lambda_iam.py``
    (``wire_lambda_iam``). Note that ``grant_assume_role`` only grants the GRANTEE
    exec role the ``sts:AssumeRole`` permission (identity side) — per the CDK docs
    it does NOT edit this role's trust policy — so it alone would leave the
    ``AccountPrincipal`` placeholder in place. ``lambda_iam.py`` therefore ALSO
    REPLACES each role's ``AssumeRolePolicyDocument`` via an L1 (``CfnRole``)
    property override so the shipped trust names EXACTLY the intended exec roles:
    ``DocumentsAccessRole`` trusts the ``read_document`` + ``search_documents`` exec
    roles; ``DocumentsWriteRole`` trusts ONLY the ``reply`` exec role. A property
    override fully replaces the constructor-generated document, so this temporary
    ``AccountPrincipal`` placeholder does NOT appear in the synthesized template.
    Until that wiring runs, the account-principal trust is the intended temporary
    state (closed in practice — no identity holds the matching assume grant).

AWS documentation references:
    - DynamoDB IAM action strings ``dynamodb:GetItem`` / ``dynamodb:Query`` /
      ``dynamodb:UpdateItem`` (data-plane actions):
      https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/rbac-iam-actions.html
      read-only action example (GetItem/Query):
      https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/read-only-permissions-on-table-items.html
    - ``aws_cdk.aws_iam.Role`` (``assumed_by``, ``inline_policies``,
      ``role_name``; ``assume_role_policy`` property + ``grant_assume_role`` for
      the Lambda IAM wiring to add exec-role principals):
      https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/Role.html
    - ``aws_cdk.aws_iam.PolicyStatement`` (``actions`` / ``resources`` / ``sid``):
      https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/PolicyStatement.html
    - ``aws_cdk.aws_iam.PolicyDocument``:
      https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/PolicyDocument.html
    - ``aws_cdk.aws_iam.AccountPrincipal`` (delegates authority to the account;
      TEMPORARY trust placeholder — narrowed by the Lambda IAM wiring):
      https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_iam/AccountPrincipal.html
    - Item-level ``LeadingKeys`` policy example listing ``UpdateItem`` alongside
      ``GetItem``/``Query`` (per-request session policy that narrows these
      identity grants — implemented by the tools):
      https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_dynamodb_items.html

Functions:
    create_documents_roles: Provision DocumentsAccessRole + DocumentsWriteRole
        and return references (constructs + ARNs).
"""

from __future__ import annotations

from dataclasses import dataclass

import aws_cdk as cdk
import aws_cdk.aws_iam as iam
from constructs import Construct

#: READ identity-policy actions — exactly GetItem + Query. Both always specify a
#: partition key, which is what makes the per-request LeadingKeys session policy
#: able to confine them.
READ_ACTIONS = ["dynamodb:GetItem", "dynamodb:Query"]

#: WRITE identity-policy action — ONLY UpdateItem. UpdateItem specifies a key, so
#: LeadingKeys confines it exactly as it does GetItem/Query.
WRITE_ACTIONS = ["dynamodb:UpdateItem"]

#: Session-tag key carrying the authoritative served scope (the ABAC second
#: gate).
#:
#: MUST stay equal to ``SCOPE_TAG_KEY`` in ``interceptor/scoped_credentials.py``:
#: the interceptor passes the tag under this key on ``AssumeRole`` and the
#: identity policies below resolve it as ``${aws:PrincipalTag/<key>}``. The two
#: literals live in different bundles (the interceptor Lambda asset excludes
#: ``cdk/``) so they cannot share a constant; ``tests/test_scope_tag_abac.py``
#: pins the equality instead. A mismatch fails CLOSED — the ``Null`` presence
#: guard below denies every request rather than widening access.
SCOPE_TAG_KEY = "scope"


def _scope_tag_conditions() -> dict[str, dict[str, object]]:
    """Build the ABAC condition block that confines a role to its tagged scope.

    SECOND GATE. Before this, both identity policies granted their actions on the
    WHOLE table and the only partition constraint lived in the per-request inline
    session policy built by the interceptor
    (``interceptor/scoped_credentials.py:build_session_policy``). Correctness
    therefore rested on a single enforcement point: any ``AssumeRole`` on these
    roles that omitted the session policy yielded full cross-tenant read/write.
    This condition moves a partition constraint INTO the role's own identity
    policy, so the role cannot read or write outside the scope its session was
    tagged with, whatever the caller does or forgets to do.

    The block carries two guards, ANDed:

    - ``ForAllValues:StringLike`` on ``dynamodb:LeadingKeys`` equal to
      ``${aws:PrincipalTag/scope}`` — the request's partition key(s) must match
      the session tag. ``StringLike`` (not ``StringEquals``) is REQUIRED here:
      AWS documents that "if you include a multivalued string context key in
      your policy with a wildcard or a variable, you must also use the
      ``StringLike`` condition operator", and ``dynamodb:LeadingKeys`` is
      multivalued. The tag value itself contains no wildcard — the interceptor
      rejects ``*`` / ``?`` in a tag value before assuming (see
      ``_scope_tag_or_raise`` there), so ``StringLike`` degenerates to an exact
      match and cannot be widened through the variable.
    - ``Null`` presence checks on BOTH ``dynamodb:LeadingKeys`` (``"false"`` =
      the key must be present) and ``aws:PrincipalTag/scope``. The first closes
      the documented ``ForAllValues`` footgun — a ``ForAllValues`` match is
      vacuously TRUE when the request key is absent or resolves to an empty set,
      which would let a keyless request through. The second means an UNTAGGED
      session is denied by this policy even if the trust-policy tag requirement
      in ``cdk/lambda_iam.py`` were ever relaxed: two independent guards, not one.
      ``Null`` deliberately takes literal values — AWS documents that a policy
      variable cannot be used with the ``Null`` operator.

    This is ANDed with, and does not replace, the per-request session policy:
    the effective permissions are the INTERSECTION of the role's identity policy
    and the session policy, so both must allow the partition.

    AWS documentation references:
        - Policy variables are substituted in condition VALUES with string/ARN
          operators; ``Null`` cannot take a policy variable:
          https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html
          https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html
        - A multivalued context key combined with a variable REQUIRES
          ``StringLike``:
          https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-single-vs-multi-valued-context-keys.html
        - ``aws:PrincipalTag`` is in the request context for a role using SESSION
          TAGS, and is usable in the ``Condition`` element of policies:
          https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html
          https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html
        - ``ForAllValues`` "returns true if there are no keys in the request, or
          if the key values resolve to a null data set" — the footgun the ``Null``
          guard closes:
          https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-policy-checks.html
        - ``dynamodb:LeadingKeys`` fine-grained access control:
          https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/specifying-conditions.html

    Returns:
        The ``conditions`` mapping for an ``iam.PolicyStatement``.
    """
    principal_tag_key = f"aws:PrincipalTag/{SCOPE_TAG_KEY}"
    return {
        "ForAllValues:StringLike": {
            "dynamodb:LeadingKeys": [f"${{{principal_tag_key}}}"],
        },
        "Null": {
            "dynamodb:LeadingKeys": "false",
            principal_tag_key: "false",
        },
    }


@dataclass
class DocumentsRoles:
    """Container for the scoped DynamoDB role references.

    BOTH the ``iam.Role`` constructs AND their ARNs are exposed so the Lambda IAM
    wiring can (a) add ``sts:AssumeRole`` grants on each tool exec role (via the
    ARNs / constructs) and (b) complete the trust-policy principals (via
    ``role.grant_assume_role(...)`` /
    ``role.assume_role_policy.add_statements(...)`` on the constructs).

    Attributes:
        documents_access_role: The DocumentsAccessRole construct (READ:
            GetItem/Query). Exposed so the Lambda IAM wiring can attach the
            read-tool exec roles as trust principals.
        documents_access_role_arn: The DocumentsAccessRole ARN (for the
            ``DOCUMENTS_ACCESS_ROLE_ARN`` env var / read-tool ``sts:AssumeRole``
            grant wired in ``cdk/lambda_iam.py``).
        documents_write_role: The DocumentsWriteRole construct (WRITE:
            UpdateItem only). Exposed so the Lambda IAM wiring can attach the
            ``reply`` exec role as the sole trust principal.
        documents_write_role_arn: The DocumentsWriteRole ARN (for the
            ``DOCUMENTS_WRITE_ROLE_ARN`` env var / ``reply`` ``sts:AssumeRole``
            grant wired in ``cdk/lambda_iam.py``).
    """

    documents_access_role: iam.Role
    documents_access_role_arn: str
    documents_write_role: iam.Role
    documents_write_role_arn: str


def create_documents_roles(
    scope: Construct,
    documents_table_arn: str,
) -> DocumentsRoles:
    """Create DocumentsAccessRole (read) and DocumentsWriteRole (write).

    Each role gets a broad identity policy that a per-request STS session policy
    (implemented by the tool Lambdas) narrows to a single served partition via
    ``dynamodb:LeadingKeys``.

    Trust policy: created with a TEMPORARY ``iam.AccountPrincipal`` placeholder
    because the tool Lambda execution roles that must be the real trust
    principals do not exist yet at this point in synthesis (they are created in
    ``scoped_credentials_stack.py`` after ``create_data_resources()``). The wiring in
    ``cdk/lambda_iam.py`` narrows the trust to the specific exec roles using the
    exposed constructs — see the module docstring's trust-policy ordering note.

    Args:
        scope: The CDK Stack or Construct to attach the roles to.
        documents_table_arn: The ``DocumentsTable`` ARN the identity policies
            grant access to.

    Returns:
        DocumentsRoles with both role constructs and both role ARNs.
    """
    # TEMPORARY trust placeholder (narrowed to the exec roles in lambda_iam.py).
    # AccountPrincipal delegates the assume decision to identity-based policies
    # in THIS account; nothing can assume until that wiring grants sts:AssumeRole
    # to the specific tool exec roles. See the module docstring.
    account_id = cdk.Stack.of(scope).account
    placeholder_trust = iam.AccountPrincipal(account_id)

    documents_access_role = iam.Role(
        scope,
        "DocumentsAccessRole",
        role_name="DocumentsAccessRole",
        assumed_by=placeholder_trust,
        description=(
            "READ role (GetItem/Query on DocumentsTable). Assumed by the REQUEST "
            "INTERCEPTOR (not the tools) with a per-request LeadingKeys session "
            "policy; the interceptor vends the scoped creds to "
            "read_document/search_documents. Trust narrowed to the interceptor exec "
            "role in lambda_iam.py."
        ),
        inline_policies={
            "DocumentsReadAllScopes": iam.PolicyDocument(
                statements=[
                    iam.PolicyStatement(
                        sid="DocumentsReadAllScopes",
                        effect=iam.Effect.ALLOW,
                        actions=READ_ACTIONS,
                        resources=[documents_table_arn],
                        # SECOND GATE: the Resource stays table-wide — the
                        # statement name is still accurate on that point — but
                        # this condition now confines the grant to the partition
                        # named by the session's `scope` tag, so the role can no
                        # longer read every partition even if a caller omits the
                        # per-request session policy. See _scope_tag_conditions()
                        # for the operator choices.
                        conditions=_scope_tag_conditions(),
                    ),
                    # Hardening: explicit Deny on Query against ANY secondary
                    # index of the table. The Allow above grants Query only on the
                    # table ARN (not `.../index/*`), so an index Query is already
                    # implicitly denied; this makes it EXPLICIT and future-proof.
                    # WHY it matters: `dynamodb:LeadingKeys` on an INDEX refers to
                    # the INDEX partition key, not the table partition key, so the
                    # per-request LeadingKeys session policy (keyed on the table
                    # partition `served_scope`) would NOT confine an index Query.
                    # Index access must therefore be denied rather than assumed
                    # unreachable (the table has no GSI today — protection by
                    # absence is not enough).
                    # Index ARN shape `table/<name>/index/*` per AWS docs
                    # (iam-policy-specific-table-indexes.html); LeadingKeys index
                    # semantics per specifying-conditions.html.
                    iam.PolicyStatement(
                        sid="DenyIndexQuery",
                        effect=iam.Effect.DENY,
                        actions=["dynamodb:Query"],
                        resources=[f"{documents_table_arn}/index/*"],
                    ),
                ]
            )
        },
    )

    documents_write_role = iam.Role(
        scope,
        "DocumentsWriteRole",
        role_name="DocumentsWriteRole",
        assumed_by=placeholder_trust,
        description=(
            "WRITE role (UpdateItem only on DocumentsTable). Assumed by the REQUEST "
            "INTERCEPTOR (not the reply tool) with a per-request LeadingKeys write "
            "session policy; the interceptor vends the scoped write creds to reply. "
            "Trust narrowed to the interceptor exec role in lambda_iam.py."
        ),
        inline_policies={
            "DocumentsWriteAllScopes": iam.PolicyDocument(
                statements=[
                    iam.PolicyStatement(
                        sid="DocumentsWriteAllScopes",
                        effect=iam.Effect.ALLOW,
                        actions=WRITE_ACTIONS,
                        resources=[documents_table_arn],
                        # SECOND GATE — same reasoning as the read role:
                        # table-wide Resource, but writes are confined to the
                        # session's tagged partition by the role's OWN policy,
                        # not only by the caller's session policy.
                        conditions=_scope_tag_conditions(),
                    )
                ]
            )
        },
    )

    return DocumentsRoles(
        documents_access_role=documents_access_role,
        documents_access_role_arn=documents_access_role.role_arn,
        documents_write_role=documents_write_role,
        documents_write_role_arn=documents_write_role.role_arn,
    )
